### ISSUE TITLE
Limit permissions to https://status.aws.amazon.com/ only

### ISSUE THREAD

**Issue by aidanjl** [josegonzalez/real-aws-status#14]
Thanks for this app, find it useful.
If possible I think it would be good to limit the Chrome permissions required to the specific AWS status page site.

By default the permissions are "Allow this extension to read and change all your data on websites you visit" which is just unnecessary risk.

I manually set the permission to a specific site and I keep using it. If that could be the default even better (not sure if Chrome allows setting a default site).

**Comment by josegonzalez** [comment]
Pull requests welcome :)

**Comment by fawaf** [comment]
afaik, the code in master does seem to only limit to the status website?

![2020-01-24-180730_756x306_scrot](https://user-images.githubusercontent.com/639565/73114971-75e2ad00-3ed4-11ea-99f6-98bdf48ac7c5.png)

**Comment by fawaf** [comment]
same for firefox as well.
![2020-01-24-181136_704x332_scrot](https://user-images.githubusercontent.com/639565/73115012-07521f00-3ed5-11ea-8611-cd1351ae2f31.png)

**Comment by aidanjl** [comment]
Thats great. I just uninstalled and reinstalled extension and now it only asks for permission to the single status.aws.amazon.com site. 
Not sure when this update occurred but it fully resolves this concern so I will close the issue. Thanks again.
