### ISSUE TITLE
release firefox extension

### ISSUE THREAD

**Issue by fawaf** [josegonzalez/real-aws-status#15]
i've tested that it works with no changes needed on firefox. can this be released as a firefox extension?

(bottom of https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#JavaScript_APIs section is the reason why it works)

**Comment by fawaf** [comment]
poke?

**Comment by josegonzalez** [comment]
Honestly I don't even think this plugin works, but if it does, thats cool.

If you'd like to resubmit to the firefox extension registry, I can add you to the repo and you can handle the things :)

**Comment by josegonzalez** [comment]
Sent you an invite: https://github.com/josegonzalez/real-aws-status/invitations

You're more than welcome to modify things to add credit to yourself as necessary :)

**Comment by fawaf** [comment]
> Honestly I don't even think this plugin works, but if it does, thats cool.
> 
> If you'd like to resubmit to the firefox extension registry, I can add you to the repo and you can handle the things :)

most of the plugin still works :) i'll fix up the part that doesn't (which is the icon messages)

**Comment by fawaf** [comment]
https://addons.mozilla.org/en-US/firefox/addon/realawsstatus/ experimental v0.1.0 released
